package com.brutecx.docflow_backend.audit.provenance;

/**
 * Where the correlation identifier came from.
 * Correlation must never lie:
 * - If it came from upstream (e.g., X-Request-Id), label it accordingly.
 * - If we generated it, it MUST be labeled as GENERATED.
 */
public enum CorrelationSource {
    /**
     * X-Request-Id (or equivalent) from incoming HTTP request handled by RequestCorrelationIdFilter.
     */
    REQUEST_ID,

    /**
     * Deterministically generated by the application when no real correlation was available.
     */
    GENERATED,

    /**
     * Keycloak admin event identifier (reserved for pull jobs / admin events).
     */
    ADMIN_EVENT_ID,

    /**
     * Keycloak session id / auth session id (reserved).
     */
    SESSION_ID,

    /**
     * Scheduled pull job run identifier / checkpoint id (reserved).
     */
    PULL_RUN
}
