package com.brutecx.docflow_backend.api.error;

public enum ErrorCode {

    VALIDATION_FAILED,
    CONSTRAINT_VIOLATION,
    MALFORMED_JSON,

    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_NOT_FOUND_LOCALLY,

    INVITE_NOT_FOUND,
    INVITE_DELIVERY_FAILED,

    DATA_INTEGRITY_VIOLATION,
    UPSTREAM_SERVICE_ERROR,

    TENANT_LIFECYCLE_VIOLATION,
    TENANT_CREATE_FAILED,

    BOOTSTRAP_ACTIVATION_DENIED,
    BOOTSTRAP_ACTIVATION_NOT_ALLOWED,

    SELF_ACTION_FORBIDDEN,
    LAST_MANAGER_VIOLATION,

    INVALID_ARGUMENT,
    UNAUTHORIZED,
    INTERNAL_SERVER_ERROR,

    ACCOUNT_LOCKED
}
