package com.brutecx.docflow_backend.api.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {

    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    CONSTRAINT_VIOLATION(HttpStatus.BAD_REQUEST),
    MALFORMED_JSON(HttpStatus.BAD_REQUEST),

    USER_ALREADY_EXISTS(HttpStatus.CONFLICT),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_NOT_FOUND_LOCALLY(HttpStatus.NOT_FOUND),

    INVITE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVITE_DELIVERY_FAILED(HttpStatus.BAD_GATEWAY),
    INVITE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    USER_ALREADY_TENANT_MEMBER(HttpStatus.CONFLICT),

    DATA_INTEGRITY_VIOLATION(HttpStatus.CONFLICT),
    UPSTREAM_SERVICE_ERROR(HttpStatus.BAD_GATEWAY),

    TENANT_LIFECYCLE_VIOLATION(HttpStatus.CONFLICT),
    TENANT_CREATE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),

    BOOTSTRAP_ACTIVATION_DENIED(HttpStatus.FORBIDDEN),
    BOOTSTRAP_ACTIVATION_NOT_ALLOWED(HttpStatus.CONFLICT),

    SELF_ACTION_FORBIDDEN(HttpStatus.FORBIDDEN),
    LAST_MANAGER_VIOLATION(HttpStatus.CONFLICT),

    INVALID_ARGUMENT(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    FORBIDDEN(HttpStatus.FORBIDDEN),

    ACCOUNT_LOCKED(HttpStatus.FORBIDDEN),

    AUDIT_EXPORT_SIGNING_KEY_MISSING(HttpStatus.FAILED_DEPENDENCY),
    AUDIT_VERIFY_INCLUDES_ARCHIVED_DATA(HttpStatus.CONFLICT),

    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND);

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}