package com.brutecx.docflow_backend.audit.admin;

public enum AdminAuditActionType {

    ROLE_ASSIGNED,
    ROLE_REVOKED,

    BOOTSTRAP_ACTIVATED,

    USER_ACTIVATED,
    USER_LOCKED,
    USER_DISABLED,

    USER_INVITED,
    INVITE_FAILED,
    INVITE_CLEANUP,
    INVITE_REVOKED,

    TENANT_CREATED,
    TENANT_CREATE_FAILED,
    TENANT_UPDATED,
    TENANT_SUSPENDED,
    TENANT_MUTATION_DENIED,

    LEGAL_HOLD_CREATE,
    LEGAL_HOLD_DEACTIVATE,

    RETENTION_POLICY_UPSERT,
    RETENTION_POLICY_UPSERT_FAILED
}