package com.brutecx.docflow_backend.audit.admin;

public enum AdminAuditActionType {
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    ROLE_REVOKE_FAILED,
    ROLE_ASSIGN_FAILED,

    BOOTSTRAP_ACTIVATED,

    USER_ACTIVATED,
    USER_LOCKED,
    USER_DISABLED,
    USER_ACTIVATE_FAILED,
    USER_DISABLE_FAILED,
    USER_LOCK_FAILED,

    USER_INVITED,
    INVITE_FAILED,
    INVITE_CLEANUP,
    INVITE_REVOKED,
    INVITE_SUBJECT_BOUND,
    INVITE_SUBJECT_BIND_FAILED,
    INVITE_PURGE_FAILED,

    TENANT_CREATED,
    TENANT_CREATE_FAILED,
    TENANT_UPDATED,
    TENANT_SUSPENDED,
    TENANT_MUTATION_DENIED,

    LEGAL_HOLD_CREATE,
    LEGAL_HOLD_DEACTIVATE,

    RETENTION_POLICY_UPSERT,
    RETENTION_POLICY_UPSERT_FAILED
}