server:
  servlet:
    session:
      cookie:
        secure: true   # behind HTTPS/Nginx in prod
        same-site: none
  use-forward-headers: true
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true

spring:
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.springframework.security: INFO
docflow:
  security:
    keycloak:
      admin:
        enabled: true
        base-url: ${KEYCLOAK_ADMIN_BASE_URL}
        realm: ${KEYCLOAK_REALM}
        client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
        client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
        poll-fixed-delay-ms: ${KEYCLOAK_ADMIN_POLL_DELAY_MS}
        page-size: ${KEYCLOAK_ADMIN_PAGE_SIZE}
