spring:
  application:
    name: docflow-rest-api
  autoconfigure:
    exclude:
      # Disable RabbitMQ auto-configuration until RabbitMQ is added
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            authorization-grant-type: authorization_code
            scope: openid,profile,email,roles
#            redirect-uri: "http://localhost:8085/login/oauth2/code/{registrationId}"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: "http://brutecx.test:8085/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_AUTH_URI}
            token-uri: ${KEYCLOAK_TOKEN_URI}
            jwk-set-uri: ${KEYCLOAK_JWKS_URI}
            # IMPORTANT:
            # user-info-uri is intentionally REMOVED
            # Spring must NOT call /userinfo (it caused 401 + login failure)
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

# Actuator & metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: docflow-rest-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
  health:
    rabbit:
      enabled: false

# Server settings and session cookie configuration
server:
  error:
    include-message: never
    include-stacktrace: never
  shutdown: graceful
  servlet:
    session:
      cookie:
        http-only: true
        same-site: LAX
        secure: false

# Custom application properties
docflow:
  security:
    # Comma-separated list of allowed origins for CORS
    allowed-origins: ${DOCFLOW_ALLOWED_ORIGINS}
    keycloak-logout-uri: ${KEYCLOAK_LOGOUT_URI}
    post-logout-redirect-uri: ${DOCFLOW_POST_LOGOUT_REDIRECT}
    frontend-base-url: ${FRONTEND_BASE_URL}
# Otel configuration to disable tracing
otel:
  traces:
    exporter: none
